#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Ilia Pozhilov"

[ui]
default-command = "log"
editor = "code -w"
diff-editor = ":builtin"

[colors]
"diff removed token" = { fg = "bright red", underline = false }
"diff added token" = { fg = "bright green", underline = false }

[revsets]
bookmark-advance-to = '@-'

[revset-aliases]
'why_immutable(r)' = '(r & immutable()) | roots(r:: & immutable_heads())'
upstream = 'fork_point(@ | trunk())'
this = 'descendants(upstream..@) | upstream'

[templates]
git_push_bookmark = "git_push_bookmark_template"

[template-aliases]
subject = 'description.first_line()'
ticket = 'subject.match(regex:"^[A-Z][A-Z0-9_]*-[0-9]+: ").remove_suffix(": ").replace(regex:"^AVP-0$","")'
'remove_ticket(subject)' = 'subject.replace(regex:"^[A-Z][A-Z0-9_]*-[0-9]+:\\s*", "")'
'slugify(str)' = 'str.lower().replace(regex:"[^a-z0-9]+", "-").remove_prefix("-").remove_suffix("-")'

git_push_bookmark_template= '''
committer.email().local() ++ "/" ++
if(description,
  surround("", "/", ticket) ++
  slugify(remove_ticket(subject))
)
'''