set -g prefix C-b
bind-key C-b send-prefix

set-option -g history-limit 10000

setw -g mode-keys vi
set -g base-index 1
set -g pane-base-index 1
set -ga update-environment "VGL_DISPLAY DISPLAY PORT VSCODE_IPC_HOOK_CLI VSCODE_WORKSPACE VSCODE_GIT_IPC_HANDLE GIT_SSH_COMMAND GIT_ASKPASS"

set -g set-clipboard on
setw -g monitor-activity off
set -g visual-activity on

set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g set-titles on
set -g set-titles-string "#T"
set -g default-shell "/bin/zsh"
setw -g xterm-keys on

bind-key 0 select-window -t :10

bind-key S setw synchronize-panes
#bind-key a setw monitor-activity
bind-key M-1 select-layout main-vertical \; resize-pane -t 1 -x 181
bind-key M-2 select-layout even-vertical
bind-key M-3 select-layout main-vertical \; resize-pane -t 1 -x 105

set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M

set -g visual-bell off

setw -g window-status-current-style bg=cyan,fg=brightgreen
setw -g window-status-bell-style bg=red


bind-key C run 'killall -USR1 autossh'

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind-key '\' if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

bind-key Tab last-window

bind-key M choose-window "join-pane -t %%"

bind-key R source-file ~/.tmux.conf \; display-message "Config reloaded!"

# macOS: pbcopy/pbpaste, Linux: xclip
if-shell "uname | grep -q Darwin" \
  'bind < run "pbpaste | tmux load-buffer - ; tmux paste-buffer"' \
  ""
if-shell "uname | grep -q Darwin" \
  'bind > run "( tmux show-buffer | pbcopy ) && tmux display-message \"ok!\""' \
  'bind > run -b "( tmux show-buffer | xclip -sel clip -i ) && tmux display-message \"copied!\""'

bind-key -T copy-mode-vi WheelUpPane send-keys -X scroll-up
bind-key -T copy-mode-vi WheelDownPane send-keys -X scroll-down

# Press prefix + I to install
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "arcticicestudio/nord-tmux"
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-logging'

# macOS-only plugins
if-shell "uname | grep -q Darwin" \
  "set -g @plugin 'MunifTanjim/tmux-suspend'; set -g @plugin 'laktak/extrakto'" \
  ""

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
